'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const studio=fs.readFileSync('web/studio.js','utf8');
const app=fs.readFileSync('web/app.js','utf8');
const helpers=studio.slice(studio.indexOf('const workbookDirectoryCache='),studio.indexOf('async function mountBuilder('));
const sheets=Array.from({length:20},(_,i)=>i===0?'汇总说明':'工作表'+i);
let calls=0,fail=false;
const file={id:'file1',path:'current.xlsx',name:'当前文件.xlsx',signature:'v1'};
const state={files:[file],tables:Array.from({length:7},(_,i)=>({id:'region'+i,file_path:file.path,sheet_name:'工作表'+i,range_ref:'A1:D5',table_name:'区域'+i}))};
const c=vm.createContext({state,draft:{},api:async()=>{calls++;if(fail)throw Error('文件正在写入');return {sheets};},esc:String,studioSelect:(id,label,content)=>'<select id="'+id+'">'+content+'</select>',options:(items,selected)=>items.map(s=>'<option'+(s===selected?' selected':'')+'>'+s+'</option>').join('')});
vm.runInContext(helpers,c);
(async()=>{
  let source=await c.chartSourceContext(state.tables[1]);
  assert.equal(source.sheets.length,20,'actual directory is not limited to seven imported sheets');
  assert.equal(source.regions.length,1);
  assert.match(c.chartSourceMarkup(source,'region1'),/工作表19/);
  await c.chartSourceContext(state.tables[2]);assert.equal(calls,1,'unchanged directory is cached');
  c.draft={sourcePath:file.path,sourceSheet:'工作表19'};
  source=await c.chartSourceContext();assert.equal(source.sheet,'工作表19');assert.equal(source.missing,false);assert.equal(source.regions.length,0,'unimported sheet remains selectable');
  c.draft={sourcePath:file.path,sourceSheet:'小转大进度'};
  source=await c.chartSourceContext();assert.equal(source.missing,true);assert.match(c.chartSourceMarkup(source,''),/旧图表未改动/);
  file.signature='v2';await c.chartSourceContext();assert.equal(calls,2,'changed workbook refreshes directory');
  assert.equal(vm.runInContext('workbookDirectoryCache.size',c),1,'old directory versions are released');
  file.signature='v3';fail=true;source=await c.chartSourceContext();assert.match(source.error,/文件正在写入/);assert.equal(source.missing,false,'read failure is not confused with a deleted sheet');
  fail=false;await c.chartSourceContext();assert.equal(calls,4,'failed reads are retryable, not cached');
  const historical={id:'old',file_path:'removed.xlsx',sheet_name:'旧表',table_name:'旧区域'};
  state.tables.push(historical);c.draft={};source=await c.chartSourceContext(historical);assert.deepEqual(Array.from(source.sheets),['旧表']);assert.equal(source.missing,false,'archived series remain usable from warehouse');
  const stamp=vm.createContext({});
  vm.runInContext(app.slice(app.indexOf('function catalogStamp('),app.indexOf('function catalogStatus(')),stamp);
  assert.notEqual(stamp.catalogStamp({tables:[],files:[{id:'A',signature:'v1'}]}),stamp.catalogStamp({tables:[],files:[{id:'A',signature:'v2'}]}));
  console.log('Workbook directory: actual sheets, unimported sheets, stale source, cache recovery and archived sources passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
