const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c=vm.createContext({});vm.runInContext(fs.readFileSync('web/chart-logic.js','utf8'),c);
for(const [name,type,expected] of [['销量','number','求和'],['转化率','number','平均值'],['累计销量','number','最新值'],['门店编码','number','非空计数'],['车型','text','非空计数'],['库存','number','求和'],['首销期天数','number','平均值']])assert.equal(c.chartOperation({name,type}),expected);
const t={fields:[{name:'车型',type:'text'},{name:'周序号',type:'text'},{name:'净大定',type:'number'}]};
const d=c.chartDefaults(t);assert.equal(d.metric,'净大定');assert.equal(d.dimension,'周序号');assert.equal(d.vehicleField,'车型');
const recs=c.tableRecommendations(t,'净大定','周序号');assert.ok(recs.length>0);assert.ok(recs.every(r=>t.fields.some(f=>f.name===r.metric)&&t.fields.some(f=>f.name===r.dimension)));
assert.equal(c.isTimeField('周序号'),true);
for(const period of ['1月','12月份','2026年1月','2026/1','2026-01-01 00:00:00','2026Q3'])assert.equal(c.isPeriodColumn(period),true);
assert.equal(c.isPeriodColumn('销量'),false);
assert.equal(c.isPeriodColumn('13月'),false);
for(const name of ['26-03','26-04','8月5日','08/06','20260807','2026-08-08T00:00:00','第12周','W13','2026年第3季度','第15天'])assert.equal(c.isPeriodColumn(name),true,name);
const shortMonths={fields:['指标','统计类型','分类','26-03','26-04','26-05','总计'].map(name=>({name,type:name.includes('-')?'number':'text'}))};
assert.deepEqual(Array.from(c.periodColumns(shortMonths)),['26-03','26-04','26-05']);
assert.deepEqual(Array.from(c.rowLabelFields(shortMonths)),['指标','统计类型','分类']);
assert.equal(c.canonicalPeriodLabel('2026年1月'),'2026-01');
assert.equal(c.canonicalPeriodLabel('2026/1'),'2026-01');
assert.deepEqual(Array.from(c.orderedTemporalKeys([new Map([['2026年2月',1],['2026年1月',2]])])),['2026年1月','2026年2月']);
assert.deepEqual(Array.from(c.orderedTemporalKeys([new Map([['11月',1],['12月',2],['1月',3]])])),['11月','12月','1月']);
const wide={table_name:'车型月销量',fields:[{name:'车型',type:'text'},{name:'2026年1月',type:'number'},{name:'2026年2月',type:'number'},{name:'2026年3月',type:'number'}]};
const wideRec=c.tableRecommendations(wide);assert.equal(wideRec.length,1);assert.equal(wideRec[0].wide,true);assert.deepEqual(Array.from(wideRec[0].periods),['2026年1月','2026年2月','2026年3月']);
assert.deepEqual(Array.from(c.rowLabelFields(wide,['2026年2月','2026年3月'])),['车型']);
assert.equal(wideRec[0].vehicleField,'车型');
const mixed={fields:[{name:'项目',type:'text'},{name:'1月',type:'number'},{name:'2月',type:'number'},{name:'2026Q1',type:'number'}]};
assert.deepEqual(Array.from(c.periodColumns(mixed)),['1月','2月']);
assert.equal(c.wideOperation({table_name:'经营指标'},'项目','转化率'),'平均值');
assert.match(c.seriesWarning([{metric:'转化率',dimension:'月份',operation:'求和'}]),/不宜求和/);
assert.match(c.seriesWarning([{metric:'销量',dimension:'月份',operation:'求和'},{metric:'金额',dimension:'月份',operation:'求和'}]),/独立分面/);
const studio=fs.readFileSync('web/studio.js','utf8');
for(const id of ['studioFile','studioSheet','studioTable','fixRegion','studioRecommendations'])assert.ok(studio.includes(id));
assert.ok(studio.includes("settingsCard.className='panel studio-settings-card'"));
assert.ok(!studio.includes('settingsCard.append(details)'));
assert.ok(studio.includes('data-edit-uid'));
assert.ok(studio.includes('data-remove-uid'));
assert.ok(studio.includes('commitChartSeries(state.basket,specs,mode,draft.editUid)'));
assert.ok(studio.includes('hierarchyChoices'));
assert.ok(studio.includes('studioSelectRange'));
assert.ok(studio.includes('studioLayout'));
assert.ok(studio.includes('bindStudioPicker'));
assert.ok(studio.includes('inferChartMapping'));
assert.ok(studio.includes('previewChartSeries(state.basket,specs,draft.commitMode,draft.editUid)'));
assert.ok(studio.includes('时间趋势'));
assert.ok(studio.includes('末期分类排名'));
assert.ok(studio.includes('studioUpdate'));
assert.ok(studio.includes('seriesChoices'));
assert.ok(studio.includes('periodGrainLabel(g.grain)'));
assert.ok(studio.includes("swap.id='swapAxes'"));
assert.ok(studio.includes("state.axisSwapped=!state.axisSwapped"));
assert.ok(!studio.includes('wide:previous.wide'));
assert.ok(!studio.includes('wide:false,periods:[],uid:Date.now()'));
assert.ok(studio.includes('取消预览'));
assert.ok(studio.includes('filters:structuredClone(series.filters||[])'));
assert.ok(!studio.includes('<label>车型<select'));
assert.equal(c.chartOperation({name:'26WK27',type:'number'},{table_name:'SKU销量排名'}),'平均值');
assert.equal(c.chartValue(.4,true),'40%');
assert.equal(c.percentageSeries({metric:'转化率',operation:'非空计数'}),false);
console.log('Chart defaults, wide tables and controls: checks passed');
