const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('web/studio.js','utf8');
const controls=new Map(),summary={},shell={open:true},document={activeElement:null};let checkboxes=[],focusCalls=0;
const list={contains:element=>checkboxes.includes(element),set innerHTML(html){if(checkboxes.includes(document.activeElement))document.activeElement=null;checkboxes=Array.from(html.matchAll(/data-choice="(\d+)"([^>]*)/g),m=>({id:'seriesChoicesChoice'+m[1],type:'checkbox',dataset:{choice:m[1]},checked:m[2].includes('checked'),focus(options){assert.equal(options.preventScroll,true);focusCalls++;document.activeElement=this;}}));}};
for(const selector of ['input[type="search"]','[data-action="all"]','[data-action="clear"]','[data-action="prev"]','[data-action="next"]','[data-count]','[data-page]','.picker-pages'])controls.set(selector,{});
controls.set('[data-list]',list);
const root={querySelector:s=>controls.get(s),querySelectorAll:()=>checkboxes};
const draft={};let emitted;
const ctx=vm.createContext({draft,document,esc:s=>s,$:s=>s.endsWith('Summary')?summary:s.endsWith('Shell')?shell:root});
vm.runInContext(source.slice(source.indexOf('function bindStudioPicker('),source.indexOf('async function chartStudio(')),ctx);
const items=Array.from({length:250},(_,i)=>({value:String(i),label:'系列 '+i}));
ctx.bindStudioPicker('seriesChoices',items,['240'],values=>emitted=Array.from(values));
assert.equal(checkboxes.length,100,'only visible page builds checkbox nodes');
assert.match(controls.get('[data-count]').textContent,/已选 1 \/ 250/);
controls.get('[data-action="all"]').onclick();
assert.equal(emitted.length,250,'all selects every page, not the first 100 or first eight');
assert.equal(new Set(emitted).size,250);
controls.get('[data-action="next"]').onclick();
assert.equal(checkboxes[0].dataset.choice,'100');
assert.ok(checkboxes.every(c=>c.checked),'selections remain checked when paging');
controls.get('[data-action="clear"]').onclick();
assert.equal(emitted.length,0,'clear removes off-screen selections as well');
const search=controls.get('input[type="search"]');search.value='系列 24';search.oninput();
assert.equal(checkboxes.length,11);
controls.get('[data-action="all"]').onclick();
assert.deepEqual(emitted,['24',...Array.from({length:10},(_,i)=>String(240+i))]);
assert.match(controls.get('[data-action="all"]').textContent,/全选搜索结果/);
search.value='系列 1';search.oninput();controls.get('[data-action="all"]').onclick();
assert.equal(emitted.length,122,'selecting filtered results adds to existing selection');
const previousCheckbox=checkboxes[0];document.activeElement=previousCheckbox;previousCheckbox.checked=false;previousCheckbox.onchange();
assert.equal(emitted.length,121);
assert.ok(!emitted.includes('1'));
assert.notEqual(document.activeElement,previousCheckbox,'the replaced checkbox node no longer owns focus');
assert.equal(document.activeElement.id,previousCheckbox.id,'keyboard focus follows the same logical checkbox');
assert.equal(focusCalls,1);
document.activeElement=search;search.value='系列 1';search.oninput();
assert.equal(document.activeElement,search,'filtering keeps focus in the search input');assert.equal(focusCalls,1);
for(const action of ['clear','all']){
  const button=controls.get('[data-action="'+action+'"]');document.activeElement=button;button.onclick();
  assert.equal(document.activeElement,button,action+' must not move focus into the checkbox list');assert.equal(focusCalls,1);
}
// Restore the earlier selection so remount assertions retain their original scope.
emitted=['24',...Array.from({length:10},(_,i)=>String(240+i)),...items.filter(item=>item.label.includes('系列 1')&&item.value!=='1').map(item=>item.value)];
shell.open=false;shell.ontoggle();
ctx.bindStudioPicker('seriesChoices',items,emitted,values=>emitted=Array.from(values));
assert.equal(shell.open,false,'picker disclosure survives remount');
assert.equal(controls.get('input[type="search"]').value,'系列 1','search survives remount');
assert.match(summary.textContent,/已选 121/);
console.log('Studio picker: all pages, filtered union, clear, paging, keyboard focus and remount checks passed');
